### ISSUE TITLE
Sample code broken by signature change

### ISSUE THREAD

**Issue by betstick** [Sirtsu55/Vulray#13]
Due to https://github.com/Sirtsu55/Vulray/commit/11d41ab6ed392234d59ca749b197a52db7ee5857 the function CreateCommandBuffer() is no longer available, on which several of the samples rely. What should be used in place of this function?

**Comment by Sirtsu55** [comment]
Hi, the sample code is not updated to the latest version of Vulray, sorry. I added these changes,  because I wanted "cleanup" Vulray and only preserve parts relevant to RT. 

```
auto cmdBuf = vk::CommandBuffer();
        auto allocInfo = vk::CommandBufferAllocateInfo(pool, level, 1);
        auto _ = mDevice.allocateCommandBuffers(&allocInfo, &cmdBuf);
```

This was the code that was deleted. Here `mDevice` is a `vk::Device` and you can use this code to create the command buffer.

**Comment by Sirtsu55** [comment]
The library is in a finalized-ish state so there won't be changes to the API, unless I see demand for it. If you want you could submit a PR to the VulraySamples repo with the working code then you are welcome to do so and I'll merge it.

I'll close this for now.
